source 'https://rubygems.org'

gem 'rails', '4.2.8'
gem 'mysql2'
gem 'thin'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'houston', '~> 2.0'
gem 'bcrypt-ruby', '~> 3.1.2'
gem 'nilify_blanks'
gem 'annotate'
gem 'kaminari', '~> 0.16.1'
gem 'haml', '~> 4.0'
gem 'dynamic_form', '~> 1.1'
gem 'nifty-utils', '~> 1.0'
gem 'bunny'
gem 'apnotic'
gem 'figaro'

group :production do
  gem 'rails_serve_static_assets'
  gem 'rails_stdout_logging'
end
