source 'https://rubygems.org'

gem 'rails', '5.1.5'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'bcrypt'
gem 'nilify_blanks'
gem 'annotate'
gem 'kaminari'
gem 'haml'
gem 'dynamic_form'
gem 'nifty-utils'
gem 'bunny'
gem 'apnotic'
gem 'figaro'
gem 'authie'
gem 'log_logins'
gem 'rack-custom-proxies'
gem 'authorized_networks'

group :production do
  gem 'rails_serve_static_assets'
  gem 'rails_stdout_logging'
end
